// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArsfOnOMuIcfnw-2bFcliARMKGRz99uEQ',
    appId: '1:896933659751:web:d39df43c692bc1572780c2',
    messagingSenderId: '896933659751',
    projectId: 'genial-charter-443605-h8',
    authDomain: 'genial-charter-443605-h8.firebaseapp.com',
    storageBucket: 'genial-charter-443605-h8.firebasestorage.app',
    measurementId: 'G-JD5W456T84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChQh5N6VmRCs_7Qd0vyb5wGaFTUqyZ-l4',
    appId: '1:896933659751:android:6127eb5a9d3f388c2780c2',
    messagingSenderId: '896933659751',
    projectId: 'genial-charter-443605-h8',
    storageBucket: 'genial-charter-443605-h8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa4dD2s4yCGst6Uv7y212480eHaH6WNXE',
    appId: '1:896933659751:ios:8a6a14eb6517ba942780c2',
    messagingSenderId: '896933659751',
    projectId: 'genial-charter-443605-h8',
    storageBucket: 'genial-charter-443605-h8.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa4dD2s4yCGst6Uv7y212480eHaH6WNXE',
    appId: '1:896933659751:ios:8a6a14eb6517ba942780c2',
    messagingSenderId: '896933659751',
    projectId: 'genial-charter-443605-h8',
    storageBucket: 'genial-charter-443605-h8.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArsfOnOMuIcfnw-2bFcliARMKGRz99uEQ',
    appId: '1:896933659751:web:75b6a4d13a5c50da2780c2',
    messagingSenderId: '896933659751',
    projectId: 'genial-charter-443605-h8',
    authDomain: 'genial-charter-443605-h8.firebaseapp.com',
    storageBucket: 'genial-charter-443605-h8.firebasestorage.app',
    measurementId: 'G-531S51BFQ9',
  );
}
